name: Scrape Positive News

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours
  workflow_dispatch:         # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          SUPABASE_URL: ${ secrets.https://mcp.supabase.com/mcp?project_ref=cynutqsogvoelqqanxtq&read_only=true&features=database%2Cdebugging%2Cdevelopment%2Cfunctions%2Cbranching%2Cstorage}
          SUPABASE_KEY: ${ secrets.sb_secret_LIKxYVKA2yzsfwFim0a3DA_9qGYn0Wb}
          TELEGRAM_TOKEN: ${ secrets.8468442347:AAEq58e-gYGsOp5h2yV_7NUy-xPkVx6SGMM }
          TELEGRAM_CHAT_ID: ${ secrets.1494535103 }
        run: python scraper.py
